#!/bin/bash
# Basic support for IRIX style chkconfig
###
# chkconfig: 2345 95 20
# description: Yapster uwsgi 
# processname: yapster
###

PRODIR="/home/ec2-user/yapster_api/yapster"
PRONAME="yapster"
PIDFILE="/var/run/yapster.pid"
SOCKFILE="/var/run/yapster.sock"
LOGFILE="/home/ec2-user/yapster_api/yapster/uwsgi.yapster.log"
MODULE="yapster.wsgi:application"

case "$1" in
  start)
        echo -n "Starting yapster"
        uwsgi --processes 2 --max-requests 10000 --master --pythonpath $PRODIR\
              --chdir $PRODIR --daemonize $LOGFILE --module $MODULE\
              --socket $SOCKFILE --pidfile $PIDFILE
        echo "."
        ;;
  stop)
        echo -n "Stopping yapster"
        if [ -f $PIDFILE ]; then
            kill -INT `cat -- $PIDFILE`
            rm -f -- $PIDFILE
        fi
        echo "."
        ;;

  *)
        echo "Usage: /sbin/service new-service {start|stop}"
        exit 1
esac

exit 0

